#!/bin/bash

# Autore: GjMan78 per forum.ubuntu.it.org

# Script  work in progress. 

# DA MIGLIORARE: pulizia file temporanei

:'FUNZIONI
Aggiornamento - Aggiorna il sistema
Appunti - Copia file negli appunti
ApriLog - Apre il file indicato
CheckConnection - Test connessione
DiagnosticaAggio - Genera report aggiornamenti per il forum
DiagnosticaRete - Genera report rete per il forum
Disclaimer - Visualizza il consenso informato
FunzioniUtili - SottoMenu Funzioni
InizializzaLog - Crea il file di log 
Menu - Munu Principale
MenuForum - SottoMenu Funzioni per il forum
MenuManutenzione - Sottomenu Manutenzione
PuliziaHome - Pulisce file inutili nella home
PuliziaPacchetti - Elimina pacchetti inutilizzati
Requisiti - Installa le dipendenze necessarie
RiparazionePacchetti - Esegue riparazione pacchetti
'

# Log eventi
InizializzaLog () {

utente=${SUDO_USER}
percorso="/home/${utente}/.config/varechina/"
nomefile=$(date +%Y-%m-%d)
logfile="${percorso}${nomefile}.log"

# crea la cartella delle configurazioni se non esiste
if [ ! -d ${percorso} ]; then
  sudo -u ${utente} mkdir ${percorso}
else
# elimina log più vecchi di 7 giorni (se esistono)
  find ${percorso} -type f -mtime +7 -name '*.log' -print0 | xargs -r0 rm -- > /dev/null
fi

}


# Consenso informato

Disclaimer () {

dialog \
  --backtitle "Dichiarazione di NON responsabilità" \
  --title "LEGGI BENE!" \
  --msgbox "L'autore declina ogni responsabilità per eventuali danni diretti o indiretti e/o malesseri fisici \
	o psicologici causati dallo script.\n\nProseguendo accetti di utilizzare il software fornito a tuo rischio e \
	pericolo e dichiari di essere l'unico responsabile dei possibili danni derivanti dall'uso dello stesso.\n
	\nNon si accettano lamentele se il cane miagola o il gatto abbaia durante l'esecuzione del programma.\n
	\nPuò causare sonnolenza. Leggere attentamente il foglietto illustrativo.\n\nHave Fun! \n" 18 70 

}


# La funzione Requisiti controlla che siano installate le dipendenze necessarie ad eseguire
# tutte le sezioni del programma.
# Se i pacchetti mancano vengono installati, altrimenti passa oltre.

Requisiti (){
  
  pkg=dialog
  status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"
  if [ ! $? = 0 ] || [ ! "$status" = installed ]; then
    clear
    echo "Devo installare "${pkg}" come dipendenza necessaria. Premi INVIO per continuare"
    read
    apt-get -y install $pkg
  fi

  if [ "$XDG_SESSION_TYPE" = x11 ]; then 
    pkg=xclip
  else
    if [ "$XDG_SESSION_TYPE" = wayland ]; then 
      pkg=wl-clipboard
    else 
      return 1
    fi
  fi

  status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"
  if [ ! $? = 0 ] || [ ! "$status" = installed ]; then
    dialog \
      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
      --title "Conferma installazione dipendenze" \
      --msgbox "Devo installare ${pkg} come dipendenza necessaria.\n Premi OK per continuare" 0 0
      apt-get -y install $pkg | dialog \
                              --title "Installazione dipendenze" \
                            funzione_B  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
                              --progressbox 0 0
  fi

  pkg=inxi
  status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"
  if [ ! $? = 0 ] || [ ! "$status" = installed ]; then
    dialog \
      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
      --title "Conferma installazione dipendenze" \
      --msgbox "Devo installare ${pkg} come dipendenza necessaria.\n Premi OK per continuare" 0 0
      apt-get -y install $pkg | dialog \
                              --title "Installazione dipendenze" \
                              --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
                              --progressbox 0 0
  fi
return 0
clear
}

# Questa funzione effettua l'aggiornamento del sistema con i classici comandi

Aggiornamento (){

dialog \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --title "Conferma" \
  --yesno "Confermi l'esecuzione di questi comandi?\n\n
apt-get update \n
apt-get -y dist-upgrade" 0 0

  if [ $? -eq 1 ]; then
        return
  fi

  clear

  data=$(date)
  echo -e "\n\n ****** INIZIO LOG AGGIORNAMENTO SISTEMA ****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  echo -e "\nAPT-GET UPDATE" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  apt-get update 2>&1 | sudo -u ${utente} tee -a ${logfile}  | \
  dialog \
    --title "Aggiornamento del sistema" \
    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
    --progressbox 25 90
  cmd1=${PIPESTATUS[0]}

  echo -e "\nAPT-GET -Y DIST-UPGRADE" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  apt-get -y dist-upgrade 2>&1 | sudo -u ${utente} tee -a ${logfile}  | \
  dialog \
    --title "Aggiornamento del sistema" \
    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
    --progressbox 25 90 
  cmd2=${PIPESTATUS[0]}

  data=$(date)
  echo -e "\n\n ****** FINE LOG AGGIORNAMENTO SISTEMA ****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  if [ $cmd1 -eq 0 ] && [ $cmd2 -eq 0 ]; then
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Successo" \
	    --msgbox "Aggiornamento del sistema eseguito con successo!" 0 0
  else
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Errore" \
	    --msgbox "Ops...Qualcosa è andato storto! Controlla il log per i dettagli." 0 0
  fi
clear  
}

# Funzione di eliminazione dei file inutili.
# Da migliorare!

MenuManutenzione () {

cmd=(dialog \
	  --ok-label "Esegui" \
	  --cancel-label "Indietro" \
	  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	  --menu "Manutenzione del sistema" 0 0 0)
  
  options=(1 "Pulizia della cache e del cestino" \
           2 "Pulizia pacchetti orfani e vecchi log" \
           3 "Riparazione pacchetti bloccati o danneggiati")

  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

  if [ $? -eq 1 ]; then
        clear; return
  fi


  for choice in ${choices}; do 
        case ${choice} in
          1) PuliziaHome ;;
          2) PuliziaPacchetti ;;
          3) RiparazionePacchetti ;;
        esac 
  done

}

PuliziaHome () {
dialog \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --title "Conferma" \
  --yesno "Confermi l'esecuzione di questi comandi? \n\n rm -rf /home/$utente/.cache/* \n \
rm -rf /home/$utente/.local/share/Trash/*" 0 0

  if [ $? -eq 1 ]; then
        return
  fi

  clear

  data=$(date)
  echo -e "\n\n ****** INIZIO LOG PULIZIA FILE HOME****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  echo -e "\n${date} RM -RF /HOME/${utente}/.cache" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  rm -rf /home/$utente/.cache/* 2>&1 | sudo -u ${utente} tee -a ${logfile}  | \
    dialog \
      --title "Pulizia file temporanei" \
      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
      --progressbox 25 90 
  cmd1=${PIPESTATUS[0]}

  #echo -e "\nAPT PURGE '?CONFIG-FILES'" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  #apt-get purge '?config-files' | sudo -u ${utente} tee -a ${logfile} 2>&1 | \
  #  dialog \
  #    --title "Pulizia file temporanei" \
  #    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  #    --progressbox 25 90 
  #cmd2=${PIPESTATUS[0]}

  echo -e "\n${date} RM -RF ~/.LOCAL/SHARE/TRASH" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  rm -rf /home/${utente}/.local/share/Trash/*  2>&1 | sudo -u ${utente} tee -a ${logfile} | \
      --title "Pulizia file temporanei" \
      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
      --progressbox 25 90 
  cmd2=${PIPESTATUS[0]}

  data=$(date)
  echo -e "\n\n ****** FINE LOG PULIZIA FILE HOME ****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  if [ $cmd1 -eq 0 ] && [ $cmd2 -eq 0 ]; then
	  dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Successo" \
	    --msgbox "Eliminazione file completata" 0 0
  else
	  dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Errore" \
	    --msgbox "Ops...Qualcosa è andato storto! Controlla il log per i dettagli." 0 0
  fi
clear
}

RiparazionePacchetti (){

dialog \
  --stdout \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --title "Conferma" \
  --yesno "Confermi l'esecuzione di questi comandi? \n\n apt-get install -f \n dpkg --configure -a \n" 0 0

  if [ $? -eq 1 ]; then
        return
  fi

  clear

  data=$(date)
  echo -e "\n\n ****** INIZIO LOG RIPARAZIONE PACCHETTI ****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  echo -e "\nAPT-GET INSTALL -F" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  apt-get install -f 2>&1 | sudo -u ${utente} tee -a ${logfile} | \
  dialog \
    --title "Riparazione pacchetti" \
    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
    --progressbox 25 90 
  cmd1=${PIPESTATUS[0]}

  echo -e "\nDPKG --CONFIGURE -A" | sudo -u ${utente} tee -a ${logfile} > /dev/null

  dpkg --configure -a 2>&1 | sudo -u ${utente} tee -a ${logfile} | \
  dialog \
    --title "Riparazione pacchetti" \
    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
    --progressbox 25 90 
  cmd2=${PIPESTATUS[0]}

  data=$(date)
  echo -e "\n\n ****** FINE LOG RIPARAZIONE PACCHETTI ****** ${data} ******\n\n" | \
  sudo -u ${utente} tee -a ${logfile} > /dev/null

  if [ $cmd1 -eq 0 ] && [ $cmd2 -eq 0 ]; then
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Successo" \
	    --msgbox "Riparazione pacchetti  completata" 0 0
  else
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Errore" \
	    --msgbox "Ops...Qualcosa è andato storto! Controlla il log per i dettagli." 0 0
  fi
clear
}



PuliziaPacchetti () {

dialog \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --title "Conferma" \
  --yesno "Confermi l'esecuzione di questi comandi?\napt-get clean\napt-get autopurge\n\
apt-get purge '?config-files'\njournalctl --rotate --vacuum-size=500M" 0 0

  if [ $? -eq 1 ]; then
        return
  fi

clear

data=$(date)
echo -e "\n\n ****** INIZIO LOG PULIZIA PACCHETTI OBSOLETI ****** ${data} ******\n\n" | \
sudo -u ${utente} tee -a ${logfile} > /dev/null

echo -e "\nAPT-GET -Y AUTOPURGE" | sudo -u ${utente} tee -a ${logfile} > /dev/null

apt-get -y autopurge 2>&1 | sudo -u ${utente} tee -a ${logfile} | \
dialog \
  --title "Pulizia pacchetti obsoleti" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --progressbox 25 90 
cmd1=${PIPESTATUS[0]}

echo -e "\nAPT-GET CLEAN" | sudo -u ${utente} tee -a ${logfile} > /dev/null

apt-get clean 2>&1 | sudo -u ${utente} tee -a ${logfile} | \
dialog \
  --title "Pulizia pacchetti obsoleti" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --progressbox 25 90 
cmd2=${PIPESTATUS[0]}

echo -e "\nAPT-GET PURGE '?CONFIG-FILES'" | sudo -u ${utente} tee -a ${logfile} > /dev/null

apt-get purge '?config-files' 2>&1 | sudo -u ${utente} tee -a ${logfile} | \
dialog \
  --title "Pulizia pacchetti obsoleti" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --progressbox 25 90 
cmd3=${PIPESTATUS[0]}

echo -e "\nJOURNALCTL --ROTATE --VACUUM-SIZE=500M" | sudo -u ${utente} tee -a ${logfile} > /dev/null

journalctl --rotate --vacuum-size=500M 2>&1 | sudo -u ${utente} tee -a ${logfile}  | \
dialog \
  --title "Pulizia pacchetti obsoleti" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --progressbox 25 90 
cmd4=${PIPESTATUS[0]}

data=$(date)
echo -e "\n\n ****** FINE LOG PULIZIA PACCHETTI OBSOLETI ****** ${data} ******\n\n" | \
sudo -u ${utente} tee -a ${logfile} > /dev/null

#echo "1: ${cmd1} 2: ${cmd2} 3: ${cmd3} 4: ${cmd4} 5: ${cmd5} 6: ${cmd6} 7: ${cmd7}" && read

if [ $cmd1 -eq 0 ] && [ $cmd2 -eq 0 ] && [ $cmd3 -eq 0 ] && [ $cmd4 -eq 0 ]; then
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Successo" \
	    --msgbox "Pulizia dei pacchetti eseguita con successo!" 0 0
  else
    dialog \
	    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	    --title "Errore" \
	    --msgbox "Ops...Qualcosa è andato storto! Controlla il log per i dettagli." 0 0
  fi
clear
}

ApriLog () {

  if [  -f $1 ]; then
	  sudo -u ${utente} gio open $1 > /dev/null 2>&1
  else
    if [[ "$1" == *"installed"* ]]; then 
	    dialog \
	      --title "Errore" \
	      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	      --msgbox "Il file non esiste.\nDevi prima salvare l'elenco dei pacchetti installati" 0 0
      return 1
    else
      dialog \
	      --title "Errore" \
	      --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	      --msgbox "Il file non esiste.\nDevi prima eseguire una delle operazioni di manutenzione" 0 0
      return 1
    fi
  fi
  clear
  
  return 0
}

Appunti () {
# Restituisce 0 se la copia negli appunti funziona, 1 altrimenti
if [ "$XDG_SESSION_TYPE" = wayland ]; then
    if [ "wc -c < $1" -ge "20000" ]; then # Se il file supera i 20000 caratteri esporta il file e copia il link
        link=$(cat $1 | curl -F 'sprunge=<-' http://sprunge.us)
        echo -e "Il report eccede il limite di caratteri imposto dal forum ed è consultabile qui: "$link | wl-copy
        return
    else
    cat $1 | wl-copy
    return 
    fi
fi

if [ "$XDG_SESSION_TYPE" = x11 ]; then
    if [ "wc -c < $1" -ge "20000" ]; then # Se il file supera i 20000 caratteri esporta il file e copia il link
        link=$(cat $1 | curl -F 'sprunge=<-' http://sprunge.us)
        echo -e "Il report eccede il limite di caratteri imposto dal forum ed è consultabile qui: "$link | xclip -selection c
        return
    else
    cat $1 | xclip -selection c
    return
    fi
fi

dialog \
  --title "Errore" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --msgbox "Ambiente grafico non riconosciuto, impossibile copiare il file $1 negli appunti." 0 0
return 1

}

FunzioniUtili () {

cmdF=(dialog \
	--ok-label "Esegui" \
	--cancel-label "Indietro" \
	--backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	--menu "Funzioni (forse) Utili" 0 0 0)

optionsF=(1 "Salva elenco pacchetti installati"
          2 "Installa pacchetti da elenco salvato"
          3 "Apri file installed-software.log")

choices=$("${cmdF[@]}" "${optionsF[@]}" 2>&1 >/dev/tty)

if [ $? -eq 1 ]; then
      clear; return
fi

for choice in ${choices}; do 
  case ${choice} in
    1) 
	    sudo -u ${SUDO_USER} -E dpkg --get-selections > /home/${utente}/installed-software.log 
      dialog \
		    --ok-label "Chiudi" \
		    --extra-button \
		    --extra-label "Apri File" \
		    --title "Esportazione completata" \
		    --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
		    --msgbox "L'elenco dei pacchetti installati è stato salvato nella tua /home" 0 0

	    if [ $? -eq 0 ]; then
		    clear; return
	    else
		    sudo -u ${utente} gio open /home/${utente}/installed-software.log > /dev/null 2>&1
	    fi
	  ;;
    2)
      if  [ -e /home/${utente}/installed-software.log ]; then
		    dialog \
          --title "Attenzione!" \
          --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
          --yesno "Funzione non testata proseguire ugualmente?" 0 0
		    if [ ! $? -eq 0 ]; then
			    return
		    fi
		    dpkg --set-selections < /home/${utente}/installed-software.log && apt-get dselect-upgrade
	    else
	    	dialog \
 	        --title "Errore!" \
	        --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	        --msgbox "Manca il file installed-software.log" 0 0
	    fi 
	    ;;
    3) ApriLog /home/${utente}/installed-software.log ;;
  esac 
done
clear
}

DiagnosticaAggio () {

filetemp=$(sudo -u ${utente} mktemp)

#inxi -Fxxc0z
echo -e "[b]inxi -Fxxc0z[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

inxi -Fxxc0z | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#lsb_release -a
echo -e "[b]lsb_release -a[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

lsb_release -a | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#uname -a
echo -e "[b]uname -a[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

uname -a | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#ELENCO REPO
echo -e "[b]cat /etc/apt/sources.list[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

cat /etc/apt/sources.list | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#EVENTUALI PPA
echo -e "[b]ls -l /etc/apt/sources.list.d[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

ls -l /etc/apt/sources.list.d | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#UPDATE
echo -e "[b]apt-get update[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

apt-get update | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#UPGRADE
echo -e "[b]apt-get upgrade[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

apt-get upgrade | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi aggiornamenti" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

echo -e "*** generato automaticamente da [url=https://github.com/GjMan78/Varechina]Varechina[/url] ***" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#APRE IL FILE DA POSTARE SUL FORUM
dialog \
  --backtitle "Funzioni per forum.ubuntu-it.org" \
  --textbox ${filetemp} 25 90

#COPIA IL FILE NEGLI APPUNTI
Appunti $filetemp
if [ $? -eq 0 ]; then
  dialog \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --title "Info" \
    --msgbox "Ho copiato il report negli appunti. Incollalo sul forum senza modificare nulla." 0 0
fi
return
}

DiagnosticaRete () {


filetemp=$(sudo -u ${utente} mktemp)

#inxi -Fxxc0z
echo -e "[b]inxi -Fxxc0z[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

inxi -Fxxc0z | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#lsb_release -a
echo -e "[b]lsb_release -a[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

lsb_release -a | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#uname -a
echo -e "[b]uname -a[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

uname -a | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#lshw -c network
echo -e "[b]lshw -c network[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

lshw -c network | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#LSPCI
echo -e "[b]lspci -nnk | grep -A3 -i net[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

lspci -nnk | grep -A3 -i net | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#LSUSB
echo -e "[b]lsusb[/b]\n[/code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

lsusb | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#MOKUTIL
echo -e "[b]mokutil --sb-state[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

mokutil --sb-state | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#IWCONFIG
echo -e "[b]iwconfig[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

iwconfig | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#NMCLI RADIO
echo -e "[b]nmcli radio[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

nmcli radio | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#nmcli connection show
echo -e "[b]nmcli connection show[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

nmcli connection show | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#rfkill list
echo -e "[b]rfkill list[/b]\n[code]" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

rfkill list | sudo -u ${utente} tee -a ${filetemp} | \
  dialog \
    --title "Diagnostica problemi di rete" \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --progressbox 25 90

echo -e "[/code]\n\n" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

echo -e "*** generato automaticamente da [url=https://github.com/GjMan78/Varechina]Varechina[/url] ***" | sudo -u ${utente} tee -a ${filetemp} > /dev/null

#APRE IL FILE DA POSTARE SUL FORUM
dialog --textbox ${filetemp} 20 80

#COPIA IL FILE NEGLI APPUNTI
Appunti $filetemp
if [ $? -eq 0 ]; then
  dialog \
    --backtitle "Funzioni per forum.ubuntu-it.org" \
    --title "Info" \
    --msgbox "Ho copiato il report negli appunti. Incollalo sul forum senza modificare nulla." 0 0
fi

dialog \
  --backtitle "Funzioni per forum.ubuntu-it.org" \
  --title "Info" \
  --msgbox "Ho copiato il report negli appunti. Incollalo sul forum senza modificare nulla." 0 0
return
}

MenuForum () {

cmd=(dialog \
	  --ok-label "Esegui" \
	  --cancel-label "Indietro" \
	  --backtitle "Funzioni per forum.ubuntu-it.org" \
	  --menu "Crea un post per una richiesta di supporto" 0 0 0)
  
  options=(1 "Diagnostica problemi con gli aggiornamenti" \
           2 "Diagnostica problemi di rete" \
           3 "Apri il forum per richiedere supporto" )

  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

  if [ $? -eq 1 ]; then
        clear; return
  fi


  for choice in ${choices}; do 
        case ${choice} in
          1) DiagnosticaAggio ;;
          2) DiagnosticaRete ;;
          3) sudo -u ${utente} gio open https://forum.ubuntu-it.org/index.php ;;
        esac 
  done

}




# Menu principale dello script
Menu () {

  cmd=(dialog \
	  --ok-label "Esegui" \
	  --cancel-label "Esci" \
	  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
	  --menu "Varechina - Il BleachBit de no'antri!" 0 0 0)
  
  options=(1 "Aggiornamento del sistema"
           2 "Manutenzione del sistema"
           3 "Apri log delle operazioni effettuate"
           4 "Funzioni (forse) utili"
           5 "Funzioni per forum.ubuntu-it.org")

  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

  if [ $? -eq 1 ]; then
        clear; exit
  fi


  for choice in ${choices}; do 
        case ${choice} in
          1) Aggiornamento ;;
          2) MenuManutenzione ;;
	        3) ApriLog ${logfile} ;;
	        4) FunzioniUtili ;;
          5) MenuForum ;;
        esac 
  done
}

CheckConnection (){
  while ! ping -q -c 1 -W 1 google.com >/dev/null 2>&1; do
    echo "Questo script richiede di essere connessi ad Internet per funzionare."
    exit
  done
}

# Main 

# Controlla se lo script è eseguito con privilegi di root

if [ "$EUID" -ne 0 ];
  then echo "Per eseguire lo script devi essere root!"
       echo ""
       echo "Eseguilo così: sudo -E "$0
exit
fi

# Controlla la connessione
CheckConnection

# Controlla se le dipendenze sono soddisfatte
Requisiti

if [ $? -ne 0 ]; then
  dialog \
  --title "Errore" \
  --backtitle "Varechina - Pulizia & Manutenzione Ubuntu" \
  --msgbox "Ambiente grafico non riconosciuto, impossibile installare le dipendenze." 0 0
  exit 1
fi

InizializzaLog

Disclaimer

# Ciclo infinito che richiama la funzione Menu finché l'utente non decide di uscire.
while :; do Menu ; done
exit 0

